server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authuser
    username: "postgres"
    password: "root"
  jpa:
    hibernate:
#      criar tabelas automatico
      ddl-auto: update
      dialect: org.jibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
#  formata cor texto cmd windows
  output:
    ansi:
      enabled: Always


logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://localhost:8082'